services:
  # --- Banco de Dados Agendamento ---
  postgres_agendamento:
    build: .
    image: postgres:17
    container_name: my_agendamento_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-agendamento}
    ports:
      - "5434:5432"
    volumes:
      - agendamento_pg_data:/var/lib/postgresql/data
    networks:
      - fase3net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-agendamento}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --- Banco de Dados Pagamento ---
  postgres_pagamento:
    build: .
    image: postgres:17
    container_name: my_pagamento_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PAGAMENTO:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PAGAMENTO:-secret}
      POSTGRES_DB: ${POSTGRES_DB_PAGAMENTO:-pagamento}
    ports:
      - "5435:5432"
    volumes:
      - pagamento_pg_data:/var/lib/postgresql/data
    networks:
      - fase3net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_PAGAMENTO:-admin} -d ${POSTGRES_DB_PAGAMENTO:-pagamento}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # --- Aplicação Procpag ---
  procpag:
    image: docker.io/erickemprobr/procpag:latest
    container_name: procpag_app
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fase3net
    depends_on:
      postgres_agendamento:
        condition: service_healthy
      postgres_pagamento:
        condition: service_healthy

  # --- Rabbitmq ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação (Java)
      - "15672:15672" # Porta do Painel de Controle (Browser)
    networks:
      - fase3net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# --- Definição de Volumes Persistentes ---
volumes:
  agendamento_pg_data:
  pagamento_pg_data:

# --- Definição de Redes ---
networks:
  fase3net:
    driver: bridge