syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.adjt.historico.grpc";

import "google/protobuf/timestamp.proto";

service ConsultaHistoricoService {
  rpc ObterHistoricoPorConsultaId (ConsultaIdRequest) returns (stream ConsultaHistoricoResponse);
}

message ConsultaIdRequest {
  int32 id = 1;
}

message UsuarioResumo {
  int32 id = 1;
  string nome = 2;
  string email = 3;
}

message EspecialidadeResumo {
  int32 id = 1;
  string nome = 2;
}

message ConsultaHistoricoResponse {
  int32 id = 1;
  int32 rev = 2;
  int32 revtype = 3; // 0: ADD, 1: MOD, 2: DEL
  string data_hora = 4;
  string diagnostico = 5;
  string prescricao = 6;
  UsuarioResumo paciente = 7;
  UsuarioResumo medico = 8;
  UsuarioResumo enfermeiro = 9;
  EspecialidadeResumo especialidade = 10;
  string dt_criacao = 11;
}