ALTER TABLE IF EXISTS tb_consulta
    ADD COLUMN IF NOT EXISTS dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE IF EXISTS tb_consulta_aud
    ADD COLUMN IF NOT EXISTS dt_criacao TIMESTAMP;