server.port=8082

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
springdoc.paths-to-match=/graphql/**

spring.graphql.graphiql.path=/api/historico
spring.graphql.http.path=/api/historico-data
spring.graphql.graphiql.enabled=true

# ===================================================================
# DATA SOURCE (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5434/${POSTGRES_DB:agendamento}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true